[build]
  base = "frontend"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  VITE_API_URL = "http://localhost:8000"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
