# Generated by Django 5.2.9 on 2026-02-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_workoutday_plan_alter_workoutexercise_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
