# Generated by Django 5.2 on 2026-08-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutplan_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video_query',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
