# Generated by Django 5.2 on 2026-09-16 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_exercise_video_query_exercise_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('muscle_group', models.CharField(choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('piernas', 'Piernas'), ('hombros', 'Hombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('core', 'Core / Abdomen'), ('gluteos', 'Glúteos'), ('cardio', 'Cardio'), ('full_body', 'Full Body')], max_length=30)),
                ('equipment', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('increment_type', models.CharField(choices=[('plate', 'Placa de máquina (sumar placas)'), ('kg_2_5', 'Peso libre (+2.5 kg)'), ('kg_5', 'Peso libre (+5 kg)'), ('bodyweight', 'Peso corporal (sin incremento)'), ('custom', 'Personalizado')], default='kg_2_5', max_length=20)),
                ('plate_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Peso de 1 placa (solo si increment_type=plate)', max_digits=5, null=True)),
                ('custom_increment_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Incremento personalizado en kg', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['muscle_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoutineTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_weeks', models.IntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('current_session_index', models.PositiveIntegerField(default=0, help_text='Índice de la próxima sesión a realizar (0-based)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_routines', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workouts.routinetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Orden en el bucle: 1=A, 2=B, 3=C…')),
                ('label', models.CharField(help_text='A, B, C…', max_length=10)),
                ('focus', models.CharField(blank=True, help_text='Ej: Empuje, Tirón, Piernas', max_length=200)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.routinetemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('routine', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rpe', models.PositiveIntegerField(blank=True, help_text='1-10', null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='workouts.clientassignment')),
                ('session_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.sessiontemplate')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionExerciseSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('main', 'Principal'), ('secondary', 'Secundario')], max_length=10)),
                ('order', models.PositiveIntegerField(help_text='1-5 dentro de la sesión')),
                ('initial_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('target_reps_min', models.PositiveIntegerField(default=12)),
                ('target_reps_max', models.PositiveIntegerField(default=15)),
                ('target_sets', models.PositiveIntegerField(default=3)),
                ('rest_seconds', models.PositiveIntegerField(default=60)),
                ('notes', models.TextField(blank=True)),
                ('exercise_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.exercisetemplate')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='workouts.sessiontemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('session', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ready_to_increase', models.BooleanField(default=False)),
                ('last_evaluated_at', models.DateTimeField(auto_now=True)),
                ('times_increased', models.PositiveIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='workouts.sessionexerciseslot')),
            ],
            options={
                'unique_together': {('client', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('reps_done', models.PositiveIntegerField()),
                ('weight_used_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.sessionlog')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.sessionexerciseslot')),
            ],
            options={
                'ordering': ['slot__order', 'set_number'],
                'unique_together': {('session_log', 'slot', 'set_number')},
            },
        ),
    ]
