# Generated by Django 5.2.9 on 2026-09-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_exercisetemplate_routinetemplate_clientassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetemplate',
            name='image',
            field=models.ImageField(blank=True, help_text='Foto de la máquina o demo del ejercicio', null=True, upload_to='exercises/'),
        ),
    ]
