# Generated by Django 5.2 on 2026-10-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_exercisetemplate_image'),
    ]

    operations = [
    ]
