# Generated by Django 5.2 on 2026-10-07 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_auto_20261007_1316'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProgressAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('confirm_result', 'Confirmar resultado de serie'), ('correct_technique', 'Corregir técnica'), ('guide_to_failure', 'Guiar serie al fallo'), ('teach_progression', 'Enseñar sobrecarga progresiva'), ('reinforce_good', 'Reforzar buena ejecución'), ('explain_structure', 'Explicar estructura del entrenamiento'), ('update_structure', 'Actualizar estructura de entrenamiento'), ('other', 'Otra acción')], max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('generated_progress_point', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.clientassignment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_progress_points', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_progress_actions', to=settings.AUTH_USER_MODEL)),
                ('session_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.sessionlog')),
            ],
            options={
                'verbose_name': 'Acción de progreso del coach',
                'verbose_name_plural': 'Acciones de progreso del coach',
                'ordering': ['-created_at'],
            },
        ),
    ]
