# Generated by Django 5.2 on 2026-10-07 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_coachprogressaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseprogression',
            name='last_failure_logged',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setlog',
            name='reached_failure',
            field=models.BooleanField(default=False, help_text='El cliente llegó al fallo técnico en esta serie'),
        ),
        migrations.CreateModel(
            name='ClientLearningPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knows_structure', models.BooleanField(default=False, help_text='Conoce grupo muscular, 3 principales, 2 complementarios y siguiente sesión.')),
                ('knows_structure_verified_at', models.DateTimeField(blank=True, null=True)),
                ('executes_correctly', models.BooleanField(default=False)),
                ('executes_correctly_verified_at', models.DateTimeField(blank=True, null=True)),
                ('knows_progression', models.BooleanField(default=False)),
                ('knows_progression_verified_at', models.DateTimeField(blank=True, null=True)),
                ('trains_autonomously', models.BooleanField(default=False)),
                ('trains_autonomously_verified_at', models.DateTimeField(blank=True, null=True)),
                ('understands_evolution', models.BooleanField(default=False)),
                ('understands_evolution_verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_points', to=settings.AUTH_USER_MODEL)),
                ('executes_correctly_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('knows_progression_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('knows_structure_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trains_autonomously_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('understands_evolution_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Puntos de aprendizaje del cliente',
                'verbose_name_plural': 'Puntos de aprendizaje del cliente',
            },
        ),
        migrations.CreateModel(
            name='MonthlyProgressBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Primer día del mes del tablero')),
                ('goal', models.CharField(choices=[('grasa', 'Pérdida de grasa'), ('musculo', 'Ganancia de músculo'), ('recomposicion', 'Recomposición corporal')], max_length=20)),
                ('training_block', models.CharField(help_text='Ej: Tren Inferior (Frecuencia 2)', max_length=200)),
                ('frequency_per_week', models.PositiveIntegerField(default=2)),
                ('total_sessions', models.PositiveIntegerField(default=8)),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado')], default='activo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_boards', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tablero de progreso mensual',
                'verbose_name_plural': 'Tableros de progreso mensual',
                'ordering': ['-month'],
                'unique_together': {('client', 'month')},
            },
        ),
        migrations.CreateModel(
            name='BoardSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField(help_text='1 a 8')),
                ('week_number', models.PositiveIntegerField(help_text='1 a 4')),
                ('phase', models.CharField(choices=[('impacto', 'Impacto (Semanas 1-2)'), ('descarga', 'Descarga (Semana 3)'), ('potencia', 'Fuerza / Potencia (Semana 4)')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.monthlyprogressboard')),
            ],
            options={
                'ordering': ['session_number'],
                'unique_together': {('board', 'session_number')},
            },
        ),
        migrations.CreateModel(
            name='BoardExerciseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='1-5 en la tabla')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_entries', to='workouts.sessionexerciseslot')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='workouts.monthlyprogressboard')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('board', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='StructureChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('exercise_swap', 'Cambio de ejercicio'), ('weight_update', 'Actualización de peso'), ('sets_reps_update', 'Cambio de series/reps'), ('session_reorder', 'Reordenamiento de sesiones'), ('routine_change', 'Cambio de rutina')], max_length=40)),
                ('reason', models.TextField(help_text='Motivo del cambio que el cliente debe comprender.')),
                ('detail', models.TextField(blank=True, default='')),
                ('client_acknowledged', models.BooleanField(default=False, help_text='El cliente comprendió el motivo del cambio.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.clientassignment')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de estructura',
                'verbose_name_plural': 'Cambios de estructura',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardExerciseSessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reps_done', models.PositiveIntegerField(blank=True, null=True)),
                ('reached_failure', models.BooleanField(default=False)),
                ('coach_note', models.CharField(blank=True, default='', max_length=200)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_data', to='workouts.boardexerciseentry')),
                ('board_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_data', to='workouts.boardsession')),
            ],
            options={
                'unique_together': {('entry', 'board_session')},
            },
        ),
    ]
