# Generated by Django 5.2.5 on 2025-08-08 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lesiones',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='peso',
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('objetivo', models.CharField(blank=True, max_length=50, null=True)),
                ('experiencia', models.CharField(blank=True, max_length=50, null=True)),
                ('frecuencia', models.IntegerField(blank=True, null=True)),
                ('lesiones', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
