# Generated by Django 5.2.9 on 2026-04-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='training_type',
            field=models.CharField(choices=[('gym', 'Gimnasio (pesas/máquinas)'), ('calisthenics', 'Calistenia (peso corporal)'), ('cardio', 'Aeróbico (correr, nadar, bici)'), ('yoga', 'Yoga / Pilates'), ('mixed', 'Mixto (combinado)')], default='calisthenics', max_length=20, verbose_name='Tipo de entrenamiento preferido'),
        ),
    ]
