# Generated by Django 5.2 on 2026-10-07 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_training_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(blank=True, default='', max_length=254)),
                ('action', models.CharField(max_length=40)),
                ('target', models.CharField(blank=True, default='', max_length=254)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acción de administración',
                'verbose_name_plural': 'Acciones de administración',
                'ordering': ['-created_at'],
            },
        ),
    ]
