# Generated by Django 5.2 on 2026-10-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_adminaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='es_admin',
            field=models.BooleanField(default=False, help_text='Acceso total al panel de administracion.', verbose_name='permiso de administrador'),
        ),
    ]
